### ISSUE TITLE
Show a nicer message on invalid or no module

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#179]
```
$ ./onigumo
** (FunctionClauseError) no function clause matching in Onigumo.CLI.main/1    
    
    The following arguments were given to Onigumo.CLI.main/1:
    
        # 1
        []
    
    (onigumo 0.1.0) lib/cli.ex:2: Onigumo.CLI.main/1
    (elixir 1.14.3) lib/kernel/cli.ex:131: anonymous fn/3 in Kernel.CLI.exec_fun/2 
```

**Comment by Glutexo** [comment]
Fixed by #249.
