### ISSUE TITLE
File.Error if no urls.txt

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#216]
```
** (File.Error) could not stream "prdel/urls.txt": no such file or directory
    (elixir 1.16.0) lib/file/stream.ex:100: anonymous fn/3 in Enumerable.File.Stream.reduce/3
    (elixir 1.16.0) lib/stream.ex:1612: anonymous fn/5 in Stream.resource/3
    (elixir 1.16.0) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.16.0) lib/stream.ex:690: Stream.run/1
    (elixir 1.16.0) lib/kernel/cli.ex:136: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by Glutexo** [comment]
Duplicate of #180.
